apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-build-params
spec:
  params:
    - name: SOURCE_ARTIFACT
      type: string
      description: >-
        The Trusted Artifact URI pointing to the artifact with the application source code.
  results:
    - name: annotations
      type: array
      description: ANNOTATIONS array for buildah
    - name: labels
      type: array
      description: LABELS array for buildah
  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:470ce04569ca7219f30dfdccdd282ed4f47201b344b05c67a3497ddcd967e2b3
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/tekton/home/source

    - name: set-results
      image: registry.access.redhat.com/ubi10/ubi-minimal:10.2-1788137716@sha256:d801168f5e8b108586c27a4fd5c92e3c1e8d061084383713926e2ca61b8b6c64
      env:
        - name: ANNOTATIONS_RESULT
          value: $(results.annotations.path)
        - name: LABELS_RESULT
          value: $(results.labels.path)
      workingDir: /tekton/home/source
      script: |
        #!/bin/bash
        set -euo pipefail

        version=$(cat VERSION)
        version_major=$(cut -d . -f 1 <<< "$version")

        printf '["org.opencontainers.image.version=%s"]' "$version" > "$ANNOTATIONS_RESULT"
        printf '[
          "org.opencontainers.image.version=%s",
          "version=%s",
          "version.major=%d"
        ]' "$version" "$version" "$version_major" > "$LABELS_RESULT"
