apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-build-params
spec:
  params:
    - name: SOURCE_ARTIFACT
      type: string
      description: >-
        The Trusted Artifact URI pointing to the artifact with the application source code.
  results:
    - name: annotations
      type: array
      description: ANNOTATIONS array for buildah
    - name: labels
      type: array
      description: LABELS array for buildah
  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:d6d6048bdb5a73697ff88734a3f33c54193405b901d3f5192b8251a878623906
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/tekton/home/source

    - name: set-results
      image: registry.access.redhat.com/ubi10/ubi-minimal:10.1-1772441549@sha256:29599cb2a44f3275232bc5fc48d26e069e8ba72b710229bed6652633725aa31a
      env:
        - name: ANNOTATIONS_RESULT
          value: $(results.annotations.path)
        - name: LABELS_RESULT
          value: $(results.labels.path)
      workingDir: /tekton/home/source
      script: |
        #!/bin/bash
        set -euo pipefail

        version=$(cat VERSION)

        printf '["org.opencontainers.image.version=%s"]' "$version" > "$ANNOTATIONS_RESULT"
        printf '["org.opencontainers.image.version=%s"]' "$version" > "$LABELS_RESULT"
