apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "main"
  labels:
    appstudio.openshift.io/application: task-runner
    appstudio.openshift.io/component: task-runner
  name: task-runner-autogenerate
  namespace: rhtap-build-tenant
spec:
  params:
    - name: source-url
      value: "{{ source_url }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: pr-author
      value: "{{ body.pull_request.user.login }}"
  pipelineSpec:
    params:
      - name: source-url
      - name: source-branch
      - name: pr-author
    tasks:
      - name: autogenerate
        taskRef:
          name: autogenerate
        params:
          - name: source-url
            value: "$(params.source-url)"
          - name: source-branch
            value: "$(params.source-branch)"
          - name: pr-author
            value: "$(params.pr-author)"
          - name: git-auth-secret-name
            value: "{{ git_auth_secret }}"
  taskRunTemplate:
    serviceAccountName: build-pipeline-task-runner
