name: Test

"on":
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4

      - name: Create virtual environment
        run: |
          make .venv

      - name: Fetch submodule tags and list expected software versions
        run: |
          # Fetches tags efficiently as a side effect
          .venv/bin/devtool ls

      - name: Free up disk space (the container build needs it)
        run: |
          #!/bin/bash
          set -euo pipefail

          echo "Disk space before cleanup:"
          df -h /
          # Android consumes >12G disk space
          sudo rm -rf /usr/local/lib/android
          echo "Disk space after cleanup:"
          df -h /

      - name: Run non-container-related tests
        env:
          TEST_IMAGE: quay.io/redhat-user-workloads/rhtap-build-tenant/task-runner:on-pr-${{ github.event.pull_request.head.sha }}
        run: |
          .venv/bin/python3 -m pytest --color=yes --ignore=tests/with_container

      - name: Check if the PR changes any files that should trigger container tests
        id: changed-container-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            Containerfile
            deps/**
            tests/with_container/**

      - name: Wait for build pipeline finishes image build
        if: steps.changed-container-files.outputs.any_changed == 'true'
        env:
          RETRY_INTERVAL: 180  # 3 Minutes
          TIMEOUT: 5400  # 1.5 Hour
          IMAGE: quay.io/redhat-user-workloads/rhtap-build-tenant/task-runner:on-pr-${{ github.event.pull_request.head.sha }}
          REVISION: ${{ github.event.pull_request.head.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          total_wait=0  # in seconds
          while true; do
            if [[ $total_wait -ge $TIMEOUT ]]; then
              printf "Timeout: build pipeline does not finish within %s seconds to build the image.\n" "$TIMEOUT"
              printf "Wait it to finish and re-run this job.\n"
              exit 1
            fi
            printf "Wait %s seconds to see if build pipeline finishes ...\n" "$RETRY_INTERVAL"
            sleep $RETRY_INTERVAL
            total_wait=$((total_wait+$RETRY_INTERVAL))
            printf "Checking build pipeline ...\n"
            gh api "repos/konflux-ci/task-runner/commits/${REVISION}/check-runs" >/tmp/checkruns.json
            conclusion=$(
              jq --arg name "Red Hat Konflux / task-runner-on-pull-request" -r \
                '.check_runs[] | select(.name == $name and .status == "completed") | .conclusion' </tmp/checkruns.json
            )
            if [[ -n "$conclusion" ]]; then
              if skopeo inspect --retry-times 3 --raw "docker://${IMAGE}"; then
                printf "Image is present in the registry.\n"
                exit 0
              fi
            fi
            if [[ $conclusion == failure ]]; then
              printf "Build pipeline failed.\n"
              exit 1
            fi
          done

      - name: Run tests
        if: steps.changed-container-files.outputs.any_changed == 'true'
        env:
          TEST_IMAGE: quay.io/redhat-user-workloads/rhtap-build-tenant/task-runner:on-pr-${{ github.event.pull_request.head.sha }}
        run: |
          .venv/bin/python3 -m pytest --color=yes tests/with_container
